### ISSUE TITLE
Fatal error: Class 'Emmanix2002\Moneywave\Moneywave' not found i

### ISSUE THREAD

**Issue by moizjam** [emmanix2002/moneywave#13]
i am getting this error when i run sample.php

Fatal error: Class 'Emmanix2002\Moneywave\Moneywave' not found in E:\money-wave\moneywave-master\examples\sample.php on line 11

**Comment by emmanix2002** [comment]
This will only happen when the class is not found. Check that the path to the `autoload.php` file is correct. If you installed it via composer as a dependency, this should already be available; all you need to do then is to fix the path to the `autoload.php` file on *line 4*. If you are trying to run it as a standalone app, then you need to run `composer install`.

**Comment by moizjam** [comment]
yes i ran.. its saying php 5.6.0.. 
can you send me full files compelet files in zip so i dont need to run composer ?

**Comment by emmanix2002** [comment]
Actually I set the minimum PHP version of the library to `7.0` but you can get it installed by doing this:

`composer install --ignore-platform-reqs`

**Comment by emmanix2002** [comment]
You can also take a look at this Stackoverflow answer: https://stackoverflow.com/questions/35273522/how-to-always-use-ignore-platform-reqs-flag-when-running-composer

**Comment by moizjam** [comment]
Okay let me try with composer install --ignore-platform-reqs
i will let you know if its works or not.

**Comment by emmanix2002** [comment]
Awesome

**Comment by moizjam** [comment]
Now when i run this example/sample.php it returns me this error 

POST https://moneywave.herokuapp.com/v1/merchant/verify` resulted in a `500 Internal Server Error` response: {"status":"error","data":"Merchant Keys do not exist","message":"Merchant Keys do not exist"} '


Can you help ?

**Comment by emmanix2002** [comment]
Great, this means it's working. Now, the next step is to rename the `.env.example` file to `.env` and fill in the your own Moneywave account keys to continue testing.

**Comment by moizjam** [comment]
Already did but still same....

**Comment by emmanix2002** [comment]
Did you fill in the staging keys from your monwywave account?

**Comment by emmanix2002** [comment]
I'll be closing the issue now, let me know if you need any more help. Cheers! :)
