### ISSUE TITLE
Error on composer installation when another Guzzlehttp package exists

### ISSUE THREAD

**Issue by DanielTheGeek** [emmanix2002/moneywave#18]
**The bug**
Composer require fails to install the package and throws an error: 
` Problem 1
    - Installation request for emmanix2002/moneywave ^0.3.1 -> satisfiable by emmanix2002/moneywave[v0.3.1].
    - Conclusion: remove guzzlehttp/guzzle 7.0.1
    - Conclusion: don't install guzzlehttp/guzzle 7.0.1
    - emmanix2002/moneywave v0.3.1 requires guzzlehttp/guzzle ~6.2 -> satisfiable by guzzlehttp/guzzle[6.2.0, 6.2.1, 6.2.2, 6.2.3, 6.3.0, 6.3.1, 6.3.2, 6.3.3, 6.4.0, 6.4.1, 6.5.0, 6.5.1, 6.5.2, 6.5.3, 6.5.4, 6.5.5].
    - Can only install one of: guzzlehttp/guzzle[6.2.0, 7.0.1].`

**To Reproduce**
Steps to reproduce the behaviour:
1. composer require google/apiclient
2. composer require emmanix2002/moneywave

**Screenshots**
![image](https://user-images.githubusercontent.com/16768517/90293250-8dd34b80-de7b-11ea-938a-9e5f3c2ab247.png)

PHP Version: PHP 7.4.8

**Comment by emmanix2002** [comment]
@DanielTheGeek you can send in a PR if you've been able to work on a fix.

**Comment by emmanix2002** [comment]
Also, the error is because of a clash in their GuzzleHttp requirements; the fix is actually simply changing the guzzlehttp requirement in this repo to something like `^6.0||^7.0`

**Comment by emmanix2002** [comment]
@DanielTheGeek I've tagged a new release `0.3.2` that contains the fixes to make it possible for you to add this as a dependency in your case.
